### ISSUE TITLE
Sidecar: check user balance and nonce before sending commitments

### ISSUE THREAD

**Issue by thedevbirb** [chainbound/bolt#102]
In the context of the recent proposal of account abstraction it may be possible that a transaction changes the balance of an EOA without increasing its nonce, since it can be originated by another entity.
As such, in the sidecar we should:
- wait for the right slot before sending the commitments and
- check both balance and nonce according to the current state

**Comment by mempirate** [comment]
@namn-grg another thing to research in the AA report is which incompatiblities there are with Bolt as of now

**Comment by thedevbirb** [comment]
Actually some balances checks are already implemented, see `unstable` branch as of now: https://github.com/chainbound/bolt/blob/025d296a8c20b2fb6fb8d5d48c72b713abfd8067/bolt-sidecar/src/builder/template.rs#L86-L116
Moreover, such logic has been a bit refactored by #117 as well.
