### ISSUE TITLE
State diffs are not used for validating new preconfirmation requests

### ISSUE THREAD

**Issue by thedevbirb** [chainbound/bolt#136]
The validation of incoming preconfirmation requests is currently flawed because the nonce and balance checks are performed against the current account state (from the latest known head) but without considering prior preconfirmations (i.e., the state diffs). To solve this, we should check against both the account state and the state diffs.

Example:
We're at slot $N$ and I make two preconfirmation requests for slot $N+2$. The validation of the second preconfirmation is successful because it is not considering the temporary state difference generated from the first request.

**Comment by namn-grg** [comment]
Can we close this?
