### ISSUE TITLE
chore(sidecar): expose a version endpoint

### ISSUE THREAD

**Issue by merklefruit** [chainbound/bolt#171]
As part of our next releases, we are going to start using the Sidecar's `CARGO_PKG_VERSION` to reliably keep track of versions of the software that node operators are running. Ideally, this should also be available as a header on a per-request basis. 

This issue consists in adding this functionality with both a `version` API endpoint and an HTTP header `x-sidecar-version`.

A more generic approach could be to introduce a more elaborate `Capabilities` enum along with the version, similar to Ethereum's engine api specs, but I think this is overkill for our current needs.

**Comment by mempirate** [comment]
Good call. For the sake of continuity, this should probably be implemented as a JSON-RPC method, i.e. `bolt_getVersion`. We should also update the cargo version for this to work (it's still 0.1.0)
