### ISSUE TITLE
Bug: missed block fails to kick off sidecar round

### ISSUE THREAD

**Issue by mempirate** [chainbound/bolt#180]
## Context
To initiate a sidecar "round" i.e. submit constraints, we rely on a new block stream. However, when no block is proposed (missed), we fail to initiate the round. We should look at a more fault-tolerant way of "keeping time", perhaps subscribe to the beacon block stream instead.

## Game plan
- Is there any events stream on the [beacon-API](https://ethereum.github.io/beacon-APIs/#/Events/eventstream) that ticks no matter what? (`head` or `block`)
- If not we should rely on the system clock. The most important thing is that the logic related to timing actually fires.
- Note that we cannot use this system clock to advance the execution / consensus state, because in most cases the block for that slot will not have arrived yet. This needs to be decoupled somehow.

**Comment by merklefruit** [comment]
We can use `ethereum_consensus::clock::from_system_time()` which will tick every slot independently of any event stream.
