### ISSUE TITLE
Bug: vanilla blocks chosen by the CL

### ISSUE THREAD

**Issue by merklefruit** [chainbound/bolt#182]
Lighthouse exposes a PBS block value multiplier such that the CL will always use pbs blocks even if less profitable than vanilla ones. On testnets, it's very likely that vanilla blocks have the same or similar value compared to external block builders, due to lack of mev and private order-flow. For this reason, it can be that by default the CL might choose a vanilla block compared to a Bolt block, which might contain committed transactions.

- The "builder-boost-factor" flag hasn't been working well for us so far: https://lighthouse-book.sigmaprime.io/builders.html
- We should also explore other options and similar flags in other CLs.

**Comment by namn-grg** [comment]
After testing again, we got the lighthouse flag working. 

Other consensus clients also have similar flags available, checkout below -

- Teku - https://docs.teku.consensys.io/reference/cli#builder-bid-compare-factor
- Nimbus - https://nimbus.guide/external-block-builder.html
- Prysm - https://docs.prylabs.network/docs/advanced/builder#prioritizing-local-blocks
- Lighthouse - https://lighthouse-book.sigmaprime.io/builders.html
