### ISSUE TITLE
Create and host `forkdiff` pages for each forked PBS component

### ISSUE THREAD

**Issue by merklefruit** [chainbound/bolt#19]
## Overview

[Forkdiff](https://github.com/protolambda/forkdiff) by Protolambda is a fantastic tool to visualize diffs between two git remotes, along with detailed explanations for each change.

We should host forkdiff views (maybe all on the same website, hosted as separate HTML pages?) for these components:

- flashbots builder
- flashbots mev-boost
- flashbots mev-boost-relay

**Comment by mempirate** [comment]
> I tried to play around with `forkdiff` with some toy examples and it works great! However since it requires git operations we need to move the builder, mev-boost and relay in separate repositories and keep them as submodules here.

I think this is not a problem and we should. Also makes more sense to have them as separate repo's if this is to be the main Bolt repository.

**Comment by merklefruit** [comment]
After some attempts, I think the best way forward will be the following:

repeat for each *package*:
1. copy it to a new directory
2. make a fresh commit on that directory
3. perform forkdiff against upstream, now that both remotes have the same directory structure

In #186 I am doing some preliminary tests to at least produce diffs, as a first step.

**Comment by merklefruit** [comment]
Completed in the `host-forkdiffs` branch and deployed to Github Pages at https://chainbound.github.io/bolt-forkdiffs/
