### ISSUE TITLE
Request to Add Turkish Translation of README

### ISSUE THREAD

**Issue by Rumeyst** [chainbound/bolt#205]
Hello,

I noticed that the current README is in English and would like to offer a Turkish translation. This could help Turkish-speaking users and contributors better understand the project.

## Proposed Solution:

1. Translate the README from English to Turkish.
2. Keep technical terms in English if they don't have direct Turkish equivalents.
3. Add a link to the Turkish version at the top of the existing README.
4. Place the translated README in docs/README_tr.md to keep the documentation organized.
## Context:

I am a native Turkish speaker and can assist with the translation. The current English version is straightforward, but translating it will make it even more accessible. Let me know if you are open to this and if there are any guidelines I should follow.

Thank you!

**Comment by merklefruit** [comment]
Hi, thanks for the proposal! 

Multi-language support is something we definitely want to explore in our docs and external-facing content. 
However, this repository is mainly for the development process for which we will stick to English as the main language.

We have a separate docs website here: https://chainbound.github.io/bolt-docs/
but that is currently not open-sourced at this time.
