### ISSUE TITLE
chore(rust-packages): enhanced CI workflows

### ISSUE THREAD

**Issue by merklefruit** [chainbound/bolt#214]
Right now we have the following rust packages:

* bolt-client
* bolt-kurtosis-client
* bolt-sidecar
* bolt-boost

but CI runs only on `bolt-sidecar` changes. We should add workflows for the other packages.
Furthermore, we should configure CI actions to perform cargo fmt and clippy on top of tests.

**Comment by thedevbirb** [comment]
We have CI for every package now, so this is solved.
