### ISSUE TITLE
chore(docs): instruct on how to query your own validator indexes

### ISSUE THREAD

**Issue by merklefruit** [chainbound/bolt#215]
as mentioned by a user on discord, it's not clear how to query your own validator indexes when trying to run
a bolt node on Helder or other testnets. we should add a few lines on how to query the 
`/eth/v1/beacon/states/head/validators` endpoint to fetch this data. 

For our internal infra, we use a lighthouse beacon + validator client, beacon HTTP api running on port 4400
with the keys stored in `validator-keys/secrets` and we query validator IDs with this script:

```shell
#!/bin/bash

# Directory containing the files
DIRECTORY="./validator-keys/secrets"

# Base URL for the API
BASE_URL="http://localhost:4400/eth/v1/beacon/states/head/validators"

# Loop through all files in the directory
for FILE in "$DIRECTORY"/*; do
    # Check if FILE is a regular file
    if [ -f "$FILE" ]; then
        # Extract the filename without the path
        FILENAME=$(basename "$FILE")

        # Make the API call with the filename as the query parameter
        RESPONSE=$(curl -s -X GET "${BASE_URL}?id=${FILENAME}" -H "accept: application/json")

        # Parse the JSON response and print the 'data[0].index' field
        INDEX=$(echo "$RESPONSE" | jq -r '.data[0].index')

        # Print the index
        echo "File: $FILENAME, Index: $INDEX"
    fi
done
```

**Comment by thedevbirb** [comment]
Validator indexes support has been dropped so this issue is no more relevant.
