### ISSUE TITLE
fix: disambiguate `bolt-boost` and `mev-boost` in monorepo

### ISSUE THREAD

**Issue by merklefruit** [chainbound/bolt#229]
Having both names is confusing to a newcomer looking to learn how Bolt works.
We should either change names or improve the monorepo directory structure in such a way to improve this setup.

**Comment by mempirate** [comment]
I think we can put the mevboost fork in its own repo and do the same for the flashbots builder. This is code that is not "core" to Bolt.

**Comment by merklefruit** [comment]
That works, but then we lose the ability to build everything with a single justfile recipe for the devnet which was handy

**Comment by namn-grg** [comment]
I agree with both the points.
 
 > That works, but then we lose the ability to build everything with a single justfile recipe for the devnet which was handy

 I think we can use some bash script file to overcome this?

**Comment by mempirate** [comment]
I suggest we leave this open until we've tested the whole PBS supply chain for ease of testing. After that we can move out standalone parts.
