### ISSUE TITLE
Move proof verification logic to the sidecar

### ISSUE THREAD

**Issue by thedevbirb** [chainbound/bolt#24]
When the builder submits a bid with proofs of transaction inclusion, the relay propagates them and they're verified inside our `mev-boost` fork. However, since the sidecar is the entrypoint from the builder api and a proxy for `mev-boost` it makes sense to move proof verification there, and keep the `mev-boost` fork as light as possible.

**Comment by merklefruit** [comment]
The reason we verify proofs in mev-boost is because we might otherwise pick a best_bid that has invalid proofs and send it to the sidecar. Closing this issue for now.
