### ISSUE TITLE
fix(helix): use commit-boost signing domain for checking BLS signatures

### ISSUE THREAD

**Issue by merklefruit** [chainbound/bolt#254]
Commit-boost standardizes a different signing domain compared to the application builder one used by mev-boost during its getHeader signature generation. 

We should use it in the relay where necessary. Reference impl in commit-boost:

https://github.com/Commit-Boost/commit-boost-client/blob/main/crates/common/src/signature.rs#L81

note: using this repo to track, but the implementation should go in https://github.com/chainbound/helix

**Comment by namn-grg** [comment]
Fixed by - https://github.com/chainbound/helix/pull/9
