### ISSUE TITLE
Tool for signing a delegation message

### ISSUE THREAD

**Issue by mempirate** [chainbound/bolt#286]
## Context

In case validators want to sign constraints with another key, they need to sign a delegation message that can be used by the sidecar to signal a delegation downstream. The sidecar can then use the delegated key to sign any further constraints, omitting the need for the validator key to be used more than once.

## Implementation

We need to create a CLI tool (let's call it `bolt-delegations-cli` for now, we can always change it). This is a Rust CLI tool that runs with the following command:

```
bolt-delegations-cli generate --source keystore ./path/to/keystore --delegated-key 0x1234 --out delegations.json
```

* We can start with a single `generate` subcommand that takes the following options:
  * --source: can be either `local` or `keystore` (required)
    * if `local`, read a BLS private key as the next argument
    * if `keystore`, read a file path as the next argument
  * --delegated-key: a BLS pubkey to which the delegation messages should be signed to (required)
  * --out: the location where to output the delegations file (can default to delegations.json)

The goal of this is to be a fully offline tool that node operators will be able to use to generate delegations safely and airgap their bolt sidecar from validator client or sensitive keystore information.

### Details

* we should re-use part of the keystore implementation made by @thedevbirb in #287 
* we can also take some inspiration from the [`go-eth2-wallet`](https://github.com/wealdtech/go-eth2-wallet?tab=readme-ov-file#signing-data-and-verifying-signatures) tool

**Comment by merklefruit** [comment]
There is also a rust implementation by the Grandine core devs here: https://github.com/grandinetech/grandine/blob/309571d6d3d7b89a2af9e4b07de2bbd084d5f740/eip_2335/src/lib.rs
