### ISSUE TITLE
feat(sidecar): Remove validator indexes from signer configs

### ISSUE THREAD

**Issue by merklefruit** [chainbound/bolt#288]
Following this discussion, we should think of how to use `pubkeys` from the various signers we support (local, remote, keystore) instead of the current `--validator-indexes` flag. 

> The config refactor is very nice! Left some comments but overall great.
> 
> Wrt the signer, this is what I understand from the current flow with the Keystore:
> 
> * sidecar is started with keystore CLI flags + `validator-indexes` flag
> * at each slot, we check if the proposer duties contain one of our validator indexes
> * if so, we try to find the pubkey from the keystore and sign the constraints with it
> 
> It would be cleaner to use the keystore as source of truth for which pubkeys we can use to sign messages in the first place, instead of going through `validator_indexes`.
> 
> In particular here's how I imagined it:
> 
> * sidecar is started with keystore CLI flags
> * all pubkeys are loaded in memory when creating the keystore
> * at each slot, we check if the proposer duties contain on of our pubkeys
> * if so, simply sign it with that key
> 
> let me know your thoughts

Thanks for the great review! Yes the flow you described is indeed correct. You're right that in the context of the keystore signer the process of checking validator indexes is redundant. I have to think whether it's still needed for other type of signers though

_Originally posted by @thedevbirb in https://github.com/chainbound/bolt/issues/287#issuecomment-2404999431_

**Comment by thedevbirb** [comment]
Validator indexes support has been dropped so this is completed.
