### ISSUE TITLE
Batch calls for checking proposer status

### ISSUE THREAD

**Issue by thedevbirb** [chainbound/bolt#348]
When we check the proposer status https://github.com/chainbound/bolt/blob/unstable/bolt-sidecar/src/chain_io/manager.rs#L58-L58 we should batch calls so that we don't incur in execution client limits if you send more than >10000 public key hashes. Ideally don't send more than 5000 public key hashes at once

**Comment by mempirate** [comment]
I think probably even less than that just to be safe! We only sent like 18k in our batch and that was waaay too much
