### ISSUE TITLE
Remove contract dependencies

### ISSUE THREAD

**Issue by merklefruit** [chainbound/bolt#36]
We currently rely on the following dependencies:

- [Relic SDK](https://github.com/Relic-Protocol/relic-contracts/tree/main)

It would be nice if the `Challenger` didn't have any third party dependency in Bolt, as it means it's more ergonomic to deploy on devnets and testnets. This issue is to keep track of dependencies and eventually decide on the best strategy to remove them.

**Comment by mempirate** [comment]
Part of #206
