### ISSUE TITLE
qol(sidecar): driver initialization fails if execution client hangs

### ISSUE THREAD

**Issue by merklefruit** [chainbound/bolt#369]
When starting bolt-sidecar with an EL node that's still syncing or is otherwise unreachable, we panic during driver initialization:

```
2024-11-08T15:32:13.710198Z DEBUG bolt_sidecar::chain_io::manager: fetching 1 proposer statuses for chunk 1 of 1
Error: Failed to initialize the sidecar driver with local signer: error sending request for url (http://localhost:8545/)

Caused by:
   0: error sending request for url (http://localhost:8545/)
   1: client error (Connect)
   2: tcp connect error: Connection refused (os error 111)
   3: Connection refused (os error 111)

Location:
    /app/src/chain_io/manager.rs:116:33
```

It would be cleaner to instead output a clear message explaining that the EL node is unreachable and retrying if possible.
We could reuse the `retry_with_backoff` util that was recently added perhaps.

Just to be clear, this _is an error_ but it should be handled more gracefully.

**Comment by estensen** [comment]
With https://github.com/chainbound/bolt/pull/578 it retries for a while, but not forever. How long should we retry before giving up? @merklefruit
