### ISSUE TITLE
SSZ: Double check hash tree root calculation in `SSZContainers`

### ISSUE THREAD

**Issue by merklefruit** [chainbound/bolt#37]
The calculation for the hash tree root of a single raw transaction needs to be double checked 
and unit tested before we can start to consider it safe.

ref: https://github.com/chainbound/bolt/blob/04-29-chore_contracts_dir/bolt-contracts/src/lib/SSZContainers.sol#L75

**Comment by thedevbirb** [comment]
Closing this as we don't need anymore SSZ proofs according to recent research and work
