### ISSUE TITLE
Sidecar: commitment streams

### ISSUE THREAD

**Issue by mempirate** [chainbound/bolt#390]
## Context
Currently, the only way for the sidecar to receive commitments is by exposing an HTTP RPC endpoint. This is not ideal for most operators because of DoS & security concerns.

An easy fix would be for sidecars to subscribe to a WebSocket endpoint (the Bolt RPC / any preconf router) that acts like a firewall and relays _filtered_ commitments over this channel. The WebSocket endpoint would be a bidirectional stream where commitment responses can also be sent with low latency. Multiple WebSocket endpoints MUST be supported.

**Comment by merklefruit** [comment]
Closed as superseded by #518
