### ISSUE TITLE
Specify authorization schema for builders

### ISSUE THREAD

**Issue by thedevbirb** [chainbound/bolt#41]
Builders need to authenticate when subscribing to SSE events emitted from relays. Right now in the codebase we're using a string like this:
```
"BOLT \"<signature>\",{\"publicKey\":\"<builder_pub_key>\",\"slot\":<slot>}"
```
where `signature` refers to the JSON-stringified object appearing the in the authentication message.
However, we should discuss more about it and update the specs.

The rationale for this schema is to have a simple one that included the builder public key, a nonce-like number to avoid replay attacks and a signature

**Comment by merklefruit** [comment]
Update: we have decided to remove authorization for this endpoint, as heavy rate-limiting will be enough to prevent major dos attacks on relays. 

This task is now changing to "remove builder auth"
