### ISSUE TITLE
Meta: Bolt Registration & Authentication

### ISSUE THREAD

**Issue by merklefruit** [chainbound/bolt#45]
Docs reference: https://chainbound.github.io/bolt-docs/architecture#opt-in-procedure-for-proposers

## Bolt Opt-in for Proposers (ECDSA version)

Ethereum validators will have the option to opt-in to the Bolt protocol by registering with the Bolt Registry smart contract. 
The registration process is as follows:

1. The Proposer signs a message with their withdrawal address private key [^1] to signify that they are requesting to opt-in. The message will need to contain the Ethereum address that the proposer intends to use as signer to authenticate individual preconfirmation requests. This way, the proposer in Bolt will have a separate identity from its validator private keys for added security.
2. The Proposer sends a transaction to the Registry, requesting to opt-in into Bolt. The transaction must be sent from the same address that was specified in the signed message, which must be passed in the transaction's data. This way, the ownership of this new ECDSA key-pair is proven on-chain.
3. Once opted-in, the Proposer must add some form of collateral to guarantee economic credibility behind its preconfirmations. The specific method in which this is achieved in Bolt is left as an open point for now.

## Commitment signing

Technically, we don't need to use a specific signing scheme or signature type to produce commitments. 
However, here are a couple factors that we want to keep in mind while making this decision:

- we care about verifiability on the EVM
	- the Ethereum protocol already supports secp256k1 natively and already has a Ecrecover precompile.
	- bls12_381 signatures are used in the consensus layer, but they won't be verified on the EVM until Pectra
	- other types of signatures (e.g. ed25519) are never used in Ethereum and as such aren't the first choice
- we care about signing speed (somewhat)
	- unless signing takes way more time than expected, then this isn't really a huge priority: we anticipate network phisical latency will be the main source of latency anyway

[^1]: One alternative for node operators is to use the private key that they authenticate with on shared security protocols.

**Comment by thedevbirb** [comment]
@merklefruit I think this can be closed as we now have a standardised interface for both registration and authentication. Wdyt?

**Comment by merklefruit** [comment]
Agree!
