### ISSUE TITLE
Remove `--expiry` flag when registering operator with EigenLayer

### ISSUE THREAD

**Issue by thedevbirb** [chainbound/bolt#585]
We need the `expiry` field and the `salt` to be compliant with the EigenLayer contracts. In particular the command `bolt eigenlayer register` will call the contract `AVSDirectory.registerOperatorToAVS` (ref: https://github.com/Layr-Labs/eigenlayer-contracts/blob/testnet-holesky/src/contracts/core/AVSDirectory.sol#L64-L71). The expiry, along with the salt, are mainly security checks for avoiding the same signature to be used many times.

Since this command will produce the signature and use it immediately, we can avoid asking the user such request and produce automatically a very short timestamp expiry. The docs should be changed accordingly.

**Comment by faheelsattar** [comment]
Hey! Can i pick this? and whats the suitable timestamp we should set here?

**Comment by merklefruit** [comment]
Hi @faheelsattar, sorry for the delay. I think `current_time + 20 minutes` can be considered a sensible expiry.

Please refer to the Eigenlayer opt in guide [here](https://github.com/chainbound/bolt/blob/unstable/testnets/holesky/QUICK_START.md#5-register-your-operator-in-a-restaking-protocol) for more detail on how the salt and expiry values should be generated.

Timestamps are in UNIX format: https://www.unixtimestamp.com/

Let me know if you are still interested!

**Comment by faheelsattar** [comment]
thanks for the clarification @merklefruit. Yeah i would like to pick this

**Comment by merklefruit** [comment]
Great, assigned :)
