### ISSUE TITLE
Don't reserve all block gas for preconfs

### ISSUE THREAD

**Issue by estensen** [chainbound/bolt#597]
A proposer would probably like to reserve some gas for top-of-block MEV, but this function currently assumes that all block gas will be used for preconst. Add a param that configures how much gas a proposer wanna reserve for preconfs.

https://github.com/chainbound/bolt/blob/8dcd096b9d7b2951b2ad8cf12f5a876f158d291e/bolt-sidecar/src/state/pricing.rs#L54-L58

**Comment by mempirate** [comment]
Closed, as the formula doesn't need to take into account the max committed gas.
