### ISSUE TITLE
Decide the value of the constant `MAX_CONSTRAINTS_PER_SLOT`

### ISSUE THREAD

**Issue by thedevbirb** [chainbound/bolt#61]
In order to encode constraints using SSZ we need to provide a maximum length to list. Regarding constraints, I decided for now to just set it to `MAX_CONSTRAINTS_PER_SLOT = 256` but this is up to discussion whether this value is reasonable or not.

Other than changing the value in the codebase and in the SSZ encoding functions, we should also define this constant value in the specs website

**Comment by mempirate** [comment]
I would actually just set it to `MAX_TRANSACTIONS_PER_BLOCK`. No need to limit this I think?

**Comment by thedevbirb** [comment]
Yes, probably the best approach is setting this to `MAX_TRANSACTIONS_PER_BLOCK` just for encoding purposes and let the proposer deciding how many commitments they want to accept.
